#!/usr/bin/env python3
"""Haelt THIRD-PARTY-NOTICES.md auf dem Stand von Cargo.lock.

── WARUM ES DAS BRAUCHT ────────────────────────────────────────────────────

Dieses Projekt schreibt keine kryptografischen Primitive selbst, also stehen
fremde Crates im Kern. Deren Lizenzen verlangen Nennung, und eine Nennung, die
beim naechsten `cargo add` veraltet, ist keine.

Der Lauf ohne Argument prueft, `--schreiben` erzeugt die Datei neu.

    python3 scripts/pruefe-notices.py
    python3 scripts/pruefe-notices.py --schreiben

── WAS ER NICHT PRUEFT ─────────────────────────────────────────────────────

Ob die Lizenzen miteinander und mit Apache-2.0 OR MIT vertraeglich sind. Das
ist eine Rechtsfrage und keine Zeichenkettenpruefung.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

WURZEL = Path(__file__).resolve().parent.parent
ZIEL = WURZEL / "THIRD-PARTY-NOTICES.md"

KOPF = """# Third-party notices

This project writes no cryptographic primitives of its own, so other people's
crates sit in the middle of it. Every package below is compiled into the
workspace or into its tests, with the licence its authors declared.

Regenerated by `python3 scripts/pruefe-notices.py --schreiben`, checked in CI
against `Cargo.lock`. A notice that goes stale at the next `cargo add` is not
a notice.

"""


def tabelle() -> str:
    roh = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--locked"],
        capture_output=True,
        text=True,
        check=True,
        cwd=WURZEL,
    ).stdout
    meta = json.loads(roh)
    eigene = {p["name"] for p in meta["packages"] if p["name"].startswith("onestein-")}
    fremd = sorted(
        (
            (p["name"], p["version"], p.get("license") or "see repository")
            for p in meta["packages"]
            if p["name"] not in eigene
        ),
        key=lambda zeile: zeile[0].lower(),
    )
    zeilen = ["| Crate | Version | Licence |", "|---|---|---|"]
    zeilen += [f"| `{name}` | {version} | {lizenz} |" for name, version, lizenz in fremd]
    return KOPF + "\n".join(zeilen) + "\n", len(fremd)


def main() -> int:
    schreiben = "--schreiben" in sys.argv[1:]
    try:
        inhalt, anzahl = tabelle()
    except FileNotFoundError:
        print("pruefe-notices: cargo nicht gefunden, nicht messbar", file=sys.stderr)
        return 2
    except subprocess.CalledProcessError as fehler:
        print(f"pruefe-notices: cargo metadata scheiterte: {fehler.stderr}", file=sys.stderr)
        return 2

    if schreiben:
        ZIEL.write_text(inhalt, encoding="utf-8")
        print(f"pruefe-notices: {anzahl} Pakete geschrieben nach {ZIEL.name}.")
        return 0

    if not ZIEL.exists():
        print(f"pruefe-notices: {ZIEL.name} fehlt, {anzahl} Pakete waeren zu nennen.", file=sys.stderr)
        return 1
    vorhanden = ZIEL.read_text(encoding="utf-8")
    if vorhanden != inhalt:
        print(
            f"pruefe-notices: {ZIEL.name} weicht von Cargo.lock ab "
            f"({anzahl} Pakete). Mit --schreiben erneuern.",
            file=sys.stderr,
        )
        return 1
    print(f"pruefe-notices: {anzahl} Pakete geprueft, 0 Abweichungen.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
